package com.offline.dpadmessenger.backend.signal.store

import android.content.Context
import io.objectbox.BoxStore

/**
 * Process-wide holder for the Signal [BoxStore].
 *
 * ObjectBox allows only ONE open [BoxStore] per database directory in a process
 * — building a second throws. [SignalMessageStore] can be constructed more than
 * once (the repository, the backend factory, and the unlink path each `new` it),
 * so the actual native store is created once here and shared.
 *
 * `MyObjectBox` is generated by the ObjectBox annotation processor at build time
 * into this same package (the common package of the `@Entity` classes), so it is
 * only present after a successful KAPT build — exactly like the module's
 * protobuf-generated classes.
 */
internal object SignalObjectBox {

    /** Sub-directory name under `<app files>/objectbox/`. */
    const val DB_NAME = "dpad-signal-obx"

    @Volatile
    private var boxStore: BoxStore? = null

    fun get(context: Context): BoxStore {
        return boxStore ?: synchronized(this) {
            boxStore ?: MyObjectBox.builder()
                .androidContext(context.applicationContext)
                .name(DB_NAME)
                .build()
                .also { boxStore = it }
        }
    }
}
