package com.offline.dpadmessenger.backend.signal.store

import android.content.Context
import android.util.Log
import io.objectbox.BoxStore

/**
 * Process-wide holder for the Signal [BoxStore].
 *
 * ObjectBox allows only ONE open [BoxStore] per database directory in a process
 * — building a second throws. [SignalMessageStore] can be constructed more than
 * once (the repository, the backend factory, and the unlink path each `new` it),
 * so the actual native store is created once here and shared.
 *
 * [get] returns null (rather than throwing) if the store can't be opened, so a
 * missing native library, a locked directory, or a full disk degrades to
 * "no persistence this session" instead of crashing — the store is built inside
 * `SignalRepository.create` on the main thread, where an exception would take
 * down the whole Signal backend.
 *
 * `MyObjectBox` is generated by the ObjectBox annotation processor at build time
 * into this same package (the common package of the `@Entity` classes), so it is
 * only present after a successful KAPT build — like the module's protobuf classes.
 */
internal object SignalObjectBox {

    /** Sub-directory name under `<app files>/objectbox/`. */
    const val DB_NAME = "dpad-signal-obx"

    private const val TAG = "SignalStore"

    @Volatile
    private var boxStore: BoxStore? = null

    /**
     * The shared [BoxStore], or null if it can't be opened. Only a SUCCESSFUL
     * open is cached, so a transient failure (e.g. Keystore/native not ready) is
     * retried on the next call. Callers MUST treat null as "persistence
     * unavailable" and degrade — never crash.
     */
    fun get(context: Context): BoxStore? {
        boxStore?.let { return it }
        return synchronized(this) {
            boxStore ?: runCatching {
                MyObjectBox.builder()
                    .androidContext(context.applicationContext)
                    .name(DB_NAME)
                    .build()
            }.onFailure {
                // Catches UnsatisfiedLinkError/LinkageError (missing native lib),
                // "another store is open", disk-full, etc.
                Log.e(TAG, "ObjectBox open failed — Signal messages won't persist this session", it)
            }.getOrNull()?.also {
                boxStore = it
                Log.i(TAG, "BoxStore opened ($DB_NAME)")
            }
        }
    }
}
