import com.google.protobuf.gradle.id

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.serialization")
    id("com.google.protobuf")
}

android {
    namespace = "com.offline.dpadmessenger.backend.signal"
    compileSdk = 36
    defaultConfig {
        minSdk = 24
        ndk {
            // libsignal-android ships native code for these ABIs only.
            abiFilters.addAll(listOf("arm64-v8a", "armeabi-v7a", "x86_64"))
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }
    kotlinOptions { jvmTarget = "17" }

    packaging {
        resources.excludes.add("META-INF/AL2.0")
        resources.excludes.add("META-INF/LGPL2.1")
        resources.excludes.add("META-INF/INDEX.LIST")
    }

    // Add proto-generated Java sources to the Android java source set.
    sourceSets.getByName("main") {
        java.srcDirs(
            "build/generated/source/proto/debug/java",
            "build/generated/source/proto/release/java",
        )
    }
}

// The kotlin-android plugin provides a top-level `kotlin {}` extension
// whose sourceSets DO have a `kotlin` property. Adding the protoc output
// here makes Kotlin compile resolve the generated classes.
kotlin {
    sourceSets.getByName("main") {
        kotlin.srcDirs(
            "build/generated/source/proto/debug/java",
            "build/generated/source/proto/release/java",
        )
    }
}

// Precise per-variant dependency: make compileXxxKotlin run after
// generateXxxProto. `whenTaskAdded` fires when each task is registered,
// regardless of whether that's before or after this block evaluates.
// Naming the tasks directly avoids the test-variant glob that caused
// the circular dependency earlier.
tasks.whenTaskAdded {
    when (name) {
        "compileDebugKotlin" -> dependsOn("generateDebugProto")
        "compileReleaseKotlin" -> dependsOn("generateReleaseProto")
        "compileDebugJavaWithJavac" -> dependsOn("generateDebugProto")
        "compileReleaseJavaWithJavac" -> dependsOn("generateReleaseProto")
    }
}

// protoc + Java-lite codegen for Signal's wire-protocol .proto files
// (copied from Signal-Android into src/main/proto/).
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.1"
    }
    generateProtoTasks {
        all().forEach { task ->
            task.builtins {
                id("java") {
                    option("lite")
                }
            }
        }
    }
}

dependencies {
    api(project(":core"))

    // Signal's official primitives — ECC, IdentityKey, ProvisioningCipher,
    // SignalProtocolStore, SessionCipher, etc. Maven Central artifact owned
    // by Signal Foundation. Verify the latest version at:
    //   https://central.sonatype.com/artifact/org.signal/libsignal-android
    //
    // IMPORTANT: keep this reasonably current. Signal-Server requires the
    // `spqr` (Sparse Post-Quantum Ratchet) device capability for new
    // linked devices, and the corresponding sealed-sender wire format
    // wasn't recognized by libsignal-android 0.46.x — it would error with
    // "protobuf encoding was invalid" inside SealedSessionCipher. The
    // post-0.7x releases include the new envelope parser.
    api("org.signal:libsignal-android:0.86.5")

    // OkHttp for both the provisioning WebSocket and the authenticated
    // chat WebSocket. Signal's clients use a similar low-level approach.
    api("com.squareup.okhttp3:okhttp:4.12.0")

    // kotlinx-serialization for our own JSON persistence of the linked
    // account. The Signal wire protocol uses protobuf — generated by the
    // protobuf plugin above from src/main/proto/*.proto.
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2")

    // Lite runtime for the generated protobuf classes.
    implementation("com.google.protobuf:protobuf-javalite:3.25.1")

    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // Required by libsignal-android.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")
}
