//! The bounded inbound event queue: everything the receive path produces waits here
//! until Kotlin's `nativePollEvents` picks it up.
//!
//! This lives in its own module — rather than inline in `lib.rs` — because it is the
//! part of the catch-up path with real failure modes (unbounded growth, oversized
//! drains) and it is the part worth unit-testing. Nothing here touches JNI, rustpush
//! or any Android API, so the tests below are plain `cargo test`.
//!
//! ## Why this exists
//!
//! Apple re-sends its entire stored backlog on every APS connect (rustpush's
//! `IMClient::setup_conn` asks for it explicitly — madrid command 160, "flush cache").
//! That IS the catch-up mechanism: it's how messages received while the app was closed
//! arrive. The cost is that a phone switched on after a day or two offline decrypts
//! thousands of messages in a burst, far faster than the Kotlin side consumes them.
//!
//! Before this module, two things were unbounded:
//!
//! 1. the queue itself, which grew until the burst was consumed; and
//! 2. the drain, which handed the WHOLE queue to Kotlin in one `serde_json::to_string`
//!    → one Java `String` (UTF-16, 2x the bytes) → one `parseToJsonElement` tree
//!    (~10x again in short-lived objects) → one enormous repository batch.
//!
//! On a 938 MB phone with a ~15 MB app heap that spike is fatal: the low-memory killer
//! takes the foreground process, and the user experiences it as the phone freezing on
//! first launch. Bounding both turns one unsurvivable spike into many small ones.
//!
//! ## The counters
//!
//! The queue also tallies what it did, and prints one `CATCHUP native:` line when a
//! burst finishes. That line is the native half of the evidence in an "export logs"
//! bundle: it says how many events came through, how deep the queue ever got, and
//! whether the cap ever had to drop anything. Without it the bundle can show that the
//! phone survived, but not by how much margin — and margin is the whole question.

use serde_json::Value;
use std::collections::{HashSet, VecDeque};

/// Hard ceiling on the queue length. Sized so an ordinary few-days backlog still fits
/// end to end without dropping anything, while a pathological burst stays bounded.
pub const INBOUND_CAP: usize = 2_000;

/// Max events a single `nativePollEvents` call may return.
///
/// This is the number that actually fixes the freeze. Throughput is unaffected: the
/// transport polls back-to-back while batches come back full (see
/// `NativeRustPushTransport.startPolling`), so catch-up takes the same wall-clock time
/// — it just never allocates more than one batch at a time.
pub const POLL_BATCH_MAX: usize = 50;

/// Log a warning on the 1st drop of a burst and every this-many after, so a pathological
/// backlog leaves a clear trail without becoming its own log flood.
const DROP_LOG_EVERY: u64 = 250;

/// The queue plus the counters that make a catch-up measurable after the fact.
#[derive(Default)]
pub struct InboundQueue {
    events: VecDeque<Value>,

    // ---- lifetime totals (process-wide) ----
    queued_total: u64,
    delivered_total: u64,
    dropped_total: u64,

    // ---- current burst ----
    /// Events handed to Kotlin since the queue was last empty.
    burst_delivered: u64,
    /// Polls served since the queue was last empty.
    burst_batches: u32,
    /// Deepest the queue got during this burst — the headroom number. A burst that
    /// peaks near [`INBOUND_CAP`] means production is outrunning the drain and the cap
    /// is the only thing standing between us and the old behaviour.
    burst_peak_depth: usize,
    /// Events dropped to the cap during this burst.
    burst_dropped: u64,
    /// Whether any poll in this burst came back full. A burst of one or two stray
    /// messages is not worth a summary line; a real catch-up always trips this.
    burst_saw_full_batch: bool,
}

impl InboundQueue {
    pub fn len(&self) -> usize {
        self.events.len()
    }

    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Queue one relay-wire event, enforcing [`INBOUND_CAP`].
    ///
    /// On overflow the OLDEST event is dropped, not the newest: a live message the user
    /// is waiting on matters more than one more item of week-old backlog.
    ///
    /// Dropping is *recoverable*, which is what makes the cap safe. Every dropped
    /// event's guid is also removed from `seen` (the replay guard), so Apple's next
    /// backlog replay re-delivers it instead of the guard silently swallowing it
    /// forever. Without that removal, a capacity drop would be permanent data loss —
    /// the guard would see the guid and skip the message on every subsequent connect.
    ///
    /// Events with no `guid` field (control events like `sms_activation`, or
    /// `chat_read`, which carries `messageGuid`) simply have nothing to un-mark; they
    /// are regenerated by the next connect's state sync rather than by the replay guard.
    pub fn queue(&mut self, seen: &mut HashSet<String>, event: Value) {
        while self.events.len() >= INBOUND_CAP {
            let Some(dropped) = self.events.pop_front() else { break };
            if let Some(guid) = dropped.get("guid").and_then(|g| g.as_str()) {
                seen.remove(guid);
            }
            self.dropped_total += 1;
            self.burst_dropped += 1;
            if self.burst_dropped == 1 || self.burst_dropped % DROP_LOG_EVERY == 0 {
                log::warn!(
                    "CATCHUP native: inbound cap hit (cap={INBOUND_CAP}) — dropped {} this burst; \
                     the replay will re-deliver them",
                    self.burst_dropped
                );
            }
        }
        self.events.push_back(event);
        self.queued_total += 1;
        if self.events.len() > self.burst_peak_depth {
            self.burst_peak_depth = self.events.len();
        }
    }

    /// Take at most `max` events off the front, leaving the rest for the next poll.
    /// Order is preserved: the repository folds messages in arrival order, and a
    /// tapback or status update that arrived after its target message must stay after
    /// it.
    ///
    /// Emits the `CATCHUP native:` summary when a burst finishes.
    pub fn drain_batch(&mut self, max: usize) -> Vec<Value> {
        let n = self.events.len().min(max);
        let batch: Vec<Value> = self.events.drain(..n).collect();

        if n > 0 {
            self.delivered_total += n as u64;
            self.burst_delivered += n as u64;
            self.burst_batches += 1;
            if n >= max {
                self.burst_saw_full_batch = true;
            }
        }
        // The queue just went (or stayed) empty — if that ended a real burst, report it
        // and start the next one clean.
        if self.events.is_empty() && self.burst_batches > 0 {
            if self.burst_saw_full_batch {
                log::info!(
                    "CATCHUP native: done delivered={} batches={} batchMax={} peakDepth={} \
                     dropped={} capHeadroom={} lifetime(queued={} delivered={} dropped={})",
                    self.burst_delivered,
                    self.burst_batches,
                    max,
                    self.burst_peak_depth,
                    self.burst_dropped,
                    INBOUND_CAP.saturating_sub(self.burst_peak_depth),
                    self.queued_total,
                    self.delivered_total,
                    self.dropped_total,
                );
            }
            self.reset_burst();
        }
        batch
    }

    fn reset_burst(&mut self) {
        self.burst_delivered = 0;
        self.burst_batches = 0;
        self.burst_peak_depth = 0;
        self.burst_dropped = 0;
        self.burst_saw_full_batch = false;
    }

    // ---- accessors, for tests and diagnostics -------------------------------
    pub fn dropped_total(&self) -> u64 {
        self.dropped_total
    }
    pub fn delivered_total(&self) -> u64 {
        self.delivered_total
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn msg(guid: &str) -> Value {
        json!({ "type": "message", "guid": guid, "text": "hi" })
    }

    /// A queue primed as the receive path primes it: every queued message's guid is
    /// also recorded in the replay guard.
    fn queue_n(n: usize) -> (InboundQueue, HashSet<String>) {
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        for i in 0..n {
            let guid = format!("G{i}");
            seen.insert(guid.clone());
            q.queue(&mut seen, msg(&guid));
        }
        (q, seen)
    }

    // ---- the cap -------------------------------------------------------------

    #[test]
    fn queue_never_exceeds_cap() {
        // The regression the freeze came from: this used to be a bare push_back, so a
        // backlog burst grew the queue without limit.
        let (q, _) = queue_n(INBOUND_CAP * 3);
        assert_eq!(q.len(), INBOUND_CAP);
    }

    #[test]
    fn overflow_drops_oldest_and_keeps_newest() {
        let (mut q, _) = queue_n(INBOUND_CAP + 5);
        let first = q.events.front().unwrap()["guid"].as_str().unwrap().to_string();
        let last = q.events.back().unwrap()["guid"].as_str().unwrap().to_string();
        assert_eq!(first, "G5", "oldest 5 should have been evicted");
        assert_eq!(last, format!("G{}", INBOUND_CAP + 4), "newest must survive");
        assert_eq!(q.dropped_total(), 5);
        let _ = q.drain_batch(POLL_BATCH_MAX);
    }

    #[test]
    fn dropped_events_are_unmarked_so_the_replay_redelivers_them() {
        // The safety property of the cap. If a guid stayed in `seen` after its event
        // was dropped, the replay guard would skip that message on every future connect
        // and the user would never see it.
        let (_, seen) = queue_n(INBOUND_CAP + 3);
        for i in 0..3 {
            assert!(!seen.contains(&format!("G{i}")), "dropped G{i} must be re-deliverable");
        }
        assert!(seen.contains(&format!("G{}", INBOUND_CAP + 2)), "retained events stay guarded");
    }

    #[test]
    fn events_without_a_guid_do_not_disturb_the_guard() {
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        seen.insert("KEEP".to_string());
        for _ in 0..(INBOUND_CAP + 10) {
            q.queue(&mut seen, json!({ "type": "sms_activation", "enabled": true }));
        }
        assert_eq!(q.len(), INBOUND_CAP);
        assert!(seen.contains("KEEP"));
    }

    // ---- the drain -----------------------------------------------------------

    #[test]
    fn drain_is_capped_and_leaves_the_remainder_queued() {
        // The core of the fix: one poll can never hand Kotlin the whole backlog.
        let (mut q, _) = queue_n(INBOUND_CAP);
        let batch = q.drain_batch(POLL_BATCH_MAX);
        assert_eq!(batch.len(), POLL_BATCH_MAX);
        assert_eq!(q.len(), INBOUND_CAP - POLL_BATCH_MAX);
    }

    #[test]
    fn drain_preserves_order_across_batches() {
        // Ordering matters downstream: a tapback or read receipt that arrived after its
        // target message must still be applied after it.
        let (mut q, _) = queue_n(POLL_BATCH_MAX * 3);
        let mut order = Vec::new();
        loop {
            let batch = q.drain_batch(POLL_BATCH_MAX);
            if batch.is_empty() {
                break;
            }
            for e in batch {
                order.push(e["guid"].as_str().unwrap().to_string());
            }
        }
        let expected: Vec<String> = (0..POLL_BATCH_MAX * 3).map(|i| format!("G{i}")).collect();
        assert_eq!(order, expected);
    }

    #[test]
    fn repeated_drains_empty_the_queue_and_then_return_nothing() {
        // What tells the transport catch-up is finished: a short batch, then an empty one.
        let (mut q, _) = queue_n(POLL_BATCH_MAX + 7);
        assert_eq!(q.drain_batch(POLL_BATCH_MAX).len(), POLL_BATCH_MAX);
        assert_eq!(q.drain_batch(POLL_BATCH_MAX).len(), 7);
        assert!(q.drain_batch(POLL_BATCH_MAX).is_empty());
    }

    #[test]
    fn a_full_backlog_is_delivered_in_bounded_chunks() {
        // End-to-end shape of catch-up after the fix: every event still gets through,
        // and no single hand-off is ever larger than POLL_BATCH_MAX.
        let (mut q, _) = queue_n(INBOUND_CAP);
        let mut total = 0usize;
        let mut largest = 0usize;
        loop {
            let batch = q.drain_batch(POLL_BATCH_MAX);
            if batch.is_empty() {
                break;
            }
            largest = largest.max(batch.len());
            total += batch.len();
        }
        assert_eq!(total, INBOUND_CAP, "nothing is lost, it is only paced");
        assert_eq!(largest, POLL_BATCH_MAX, "and no hand-off exceeds one batch");
        assert_eq!(q.delivered_total(), INBOUND_CAP as u64);
    }

    // ---- the counters that end up in an export-logs bundle -------------------

    #[test]
    fn peak_depth_records_how_close_the_burst_came_to_the_cap() {
        // This is the headroom number a support bundle is read for: a peak far below
        // the cap means the drain kept up, a peak pinned AT the cap means it did not.
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        for i in 0..600 {
            q.queue(&mut seen, msg(&format!("G{i}")));
        }
        assert_eq!(q.burst_peak_depth, 600);
        // Draining does not lower the recorded peak — it is the high-water mark for the
        // whole burst, not the current depth.
        q.drain_batch(POLL_BATCH_MAX);
        assert_eq!(q.burst_peak_depth, 600);
    }

    #[test]
    fn burst_counters_reset_once_the_queue_empties() {
        let (mut q, _) = queue_n(POLL_BATCH_MAX * 2);
        while !q.drain_batch(POLL_BATCH_MAX).is_empty() {}
        assert_eq!(q.burst_delivered, 0, "a finished burst must not bleed into the next");
        assert_eq!(q.burst_batches, 0);
        assert_eq!(q.burst_peak_depth, 0);
        assert!(!q.burst_saw_full_batch);
        // Lifetime totals persist — they are what the summary reports as context.
        assert_eq!(q.delivered_total(), (POLL_BATCH_MAX * 2) as u64);
    }

    #[test]
    fn a_trickle_of_live_messages_is_not_reported_as_a_burst() {
        // The summary line has to mean something. If every single arriving message
        // logged one, the line would be worthless in a bundle — and would itself become
        // the kind of log flood this work exists to remove.
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        for i in 0..30 {
            q.queue(&mut seen, msg(&format!("L{i}")));
            let batch = q.drain_batch(POLL_BATCH_MAX);
            assert_eq!(batch.len(), 1);
            assert!(!q.burst_saw_full_batch, "a single message is never a full batch");
        }
        assert_eq!(q.delivered_total(), 30);
    }

    #[test]
    fn drops_are_counted_per_burst_and_for_the_lifetime() {
        let (mut q, _) = queue_n(INBOUND_CAP + 120);
        assert_eq!(q.burst_dropped, 120);
        assert_eq!(q.dropped_total(), 120);
        while !q.drain_batch(POLL_BATCH_MAX).is_empty() {}
        assert_eq!(q.burst_dropped, 0, "burst counter resets");
        assert_eq!(q.dropped_total(), 120, "lifetime counter does not");
    }

    #[test]
    fn a_healthy_catch_up_reports_zero_drops() {
        // The success case the bundle should show: a few days of backlog fits under the
        // cap end to end, so nothing is dropped and nothing needs re-delivering.
        let (mut q, _) = queue_n(1_500);
        while !q.drain_batch(POLL_BATCH_MAX).is_empty() {}
        assert_eq!(q.dropped_total(), 0);
        assert_eq!(q.delivered_total(), 1_500);
    }
}
