//! The bounded inbound event queue: everything the receive path produces waits here
//! until Kotlin's `nativePollEvents` picks it up.
//!
//! This lives in its own module — rather than inline in `lib.rs` — because it is the
//! part of the catch-up path with real failure modes (unbounded growth, oversized
//! drains) and it is the part worth unit-testing. Nothing here touches JNI, rustpush
//! or any Android API, so the tests below are plain `cargo test`.
//!
//! ## Why this exists
//!
//! Apple re-sends its entire stored backlog on every APS connect (rustpush's
//! `IMClient::setup_conn` asks for it explicitly — madrid command 160, "flush cache").
//! That IS the catch-up mechanism: it's how messages received while the app was closed
//! arrive. The cost is that a phone switched on after a day or two offline decrypts
//! thousands of messages in a burst, far faster than the Kotlin side consumes them.
//!
//! Before this module, two things were unbounded:
//!
//! 1. the queue itself, which grew until the burst was consumed; and
//! 2. the drain, which handed the WHOLE queue to Kotlin in one `serde_json::to_string`
//!    → one Java `String` (UTF-16, 2x the bytes) → one `parseToJsonElement` tree
//!    (~10x again in short-lived objects) → one enormous repository batch.
//!
//! On a 938 MB phone with a ~15 MB app heap that spike is fatal: the low-memory killer
//! takes the foreground process, and the user experiences it as the phone freezing on
//! first launch. Bounding both turns one unsurvivable spike into many small ones.
//!
//! ## The counters
//!
//! The queue also tallies what it did, and prints one `CATCHUP native:` line when a
//! burst finishes. That line is the native half of the evidence in an "export logs"
//! bundle: it says how many events came through, how deep the queue ever got, and
//! whether the cap ever had to drop anything. Without it the bundle can show that the
//! phone survived, but not by how much margin — and margin is the whole question.

use serde_json::Value;
use std::collections::{HashSet, VecDeque};

/// Hard ceiling on the queue length. Sized so an ordinary few-days backlog still fits
/// end to end without dropping anything, while a pathological burst stays bounded.
pub const INBOUND_CAP: usize = 2_000;

/// Max events a single `nativePollEvents` call may return.
///
/// This is the number that actually fixes the freeze. Throughput is unaffected: the
/// transport polls back-to-back while batches come back full (see
/// `NativeRustPushTransport.startPolling`), so catch-up takes the same wall-clock time
/// — it just never allocates more than one batch at a time.
pub const POLL_BATCH_MAX: usize = 50;

/// Log a warning on the 1st drop of a burst and every this-many after, so a pathological
/// backlog leaves a clear trail without becoming its own log flood.
const DROP_LOG_EVERY: u64 = 250;

/// The queue plus the counters that make a catch-up measurable after the fact.
#[derive(Default)]
pub struct InboundQueue {
    events: VecDeque<Value>,

    // ---- lifetime totals (process-wide) ----
    queued_total: u64,
    delivered_total: u64,
    dropped_total: u64,

    // ---- current burst ----
    /// Events handed to Kotlin since the queue was last empty.
    burst_delivered: u64,
    /// Polls served since the queue was last empty.
    burst_batches: u32,
    /// Deepest the queue got during this burst — the headroom number. A burst that
    /// peaks near [`INBOUND_CAP`] means production is outrunning the drain and the cap
    /// is the only thing standing between us and the old behaviour.
    burst_peak_depth: usize,
    /// Events dropped to the cap during this burst.
    burst_dropped: u64,
    /// Whether any poll in this burst came back full. A burst of one or two stray
    /// messages is not worth a summary line; a real catch-up always trips this.
    burst_saw_full_batch: bool,
}

impl InboundQueue {
    pub fn len(&self) -> usize {
        self.events.len()
    }

    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Queue one relay-wire event, enforcing [`INBOUND_CAP`].
    ///
    /// On overflow the OLDEST event is dropped, not the newest: a live message the user
    /// is waiting on matters more than one more item of week-old backlog.
    ///
    /// Dropping is *recoverable*, which is what makes the cap safe. Every dropped
    /// event's guid is also removed from `seen` (the replay guard), so Apple's next
    /// backlog replay re-delivers it instead of the guard silently swallowing it
    /// forever. Without that removal, a capacity drop would be permanent data loss —
    /// the guard would see the guid and skip the message on every subsequent connect.
    ///
    /// Events with no `guid` field (control events like `sms_activation`, or
    /// `chat_read`, which carries `messageGuid`) simply have nothing to un-mark; they
    /// are regenerated by the next connect's state sync rather than by the replay guard.
    pub fn queue(&mut self, seen: &mut HashSet<String>, event: Value) {
        while self.events.len() >= INBOUND_CAP {
            let Some(dropped) = self.events.pop_front() else { break };
            if let Some(guid) = dropped.get("guid").and_then(|g| g.as_str()) {
                seen.remove(guid);
            }
            self.dropped_total += 1;
            self.burst_dropped += 1;
            if self.burst_dropped == 1 || self.burst_dropped % DROP_LOG_EVERY == 0 {
                log::warn!(
                    "CATCHUP native: inbound cap hit (cap={INBOUND_CAP}) — dropped {} this burst; \
                     the replay will re-deliver them",
                    self.burst_dropped
                );
            }
        }
        self.events.push_back(event);
        self.queued_total += 1;
        if self.events.len() > self.burst_peak_depth {
            self.burst_peak_depth = self.events.len();
        }
    }

    /// Take at most `max` events off the front, leaving the rest for the next poll.
    /// Order is preserved: the repository folds messages in arrival order, and a
    /// tapback or status update that arrived after its target message must stay after
    /// it.
    ///
    /// Emits the `CATCHUP native:` summary when a burst finishes.
    pub fn drain_batch(&mut self, max: usize) -> Vec<Value> {
        let n = self.events.len().min(max);
        let batch: Vec<Value> = self.events.drain(..n).collect();

        if n > 0 {
            self.delivered_total += n as u64;
            self.burst_delivered += n as u64;
            self.burst_batches += 1;
            if n >= max {
                self.burst_saw_full_batch = true;
            }
        }
        // The queue just went (or stayed) empty — if that ended a real burst, report it
        // and start the next one clean.
        if self.events.is_empty() && self.burst_batches > 0 {
            if self.burst_saw_full_batch {
                log::info!(
                    "CATCHUP native: done delivered={} batches={} batchMax={} peakDepth={} \
                     dropped={} capHeadroom={} lifetime(queued={} delivered={} dropped={})",
                    self.burst_delivered,
                    self.burst_batches,
                    max,
                    self.burst_peak_depth,
                    self.burst_dropped,
                    INBOUND_CAP.saturating_sub(self.burst_peak_depth),
                    self.queued_total,
                    self.delivered_total,
                    self.dropped_total,
                );
            }
            self.reset_burst();
        }
        batch
    }

    fn reset_burst(&mut self) {
        self.burst_delivered = 0;
        self.burst_batches = 0;
        self.burst_peak_depth = 0;
        self.burst_dropped = 0;
        self.burst_saw_full_batch = false;
    }

    // ---- accessors, for tests and diagnostics -------------------------------
    pub fn dropped_total(&self) -> u64 {
        self.dropped_total
    }
    pub fn delivered_total(&self) -> u64 {
        self.delivered_total
    }
}

// ---------------------------------------------------------------------------
// Ingest activity — is the receive path busy, even when the queue is empty?
// ---------------------------------------------------------------------------

/// Reported as `idleMs` when the receive path has not seen a single message yet.
/// Large enough to read as "idle" everywhere, small enough to survive the trip through
/// JSON into a Kotlin `Long` (`u64::MAX` would not).
const IDLE_NEVER_MS: u64 = u32::MAX as u64;

/// Log the running discard tally every this-many discarded messages. Same reasoning as
/// [`DROP_LOG_EVERY`]: leave a clear trail without becoming a flood.
const DISCARD_LOG_EVERY: u64 = 250;

/// What the receive path did with one decrypted message.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Ingested {
    /// Passed both gates and was queued for Kotlin.
    Admitted,
    /// Older than `SYNC_WINDOW_MS` — dropped before marshal, queue, storage or UI.
    OutsideWindow,
    /// Kotlin already holds it, so Apple's replay of it was suppressed.
    AlreadySeen,
}

/// Counts what the receive path is doing, so Kotlin can tell "busy" from "idle" even
/// while nothing is reaching it.
///
/// ## Why this exists
///
/// Everything else in this module measures the QUEUE, and that turns out to be the wrong
/// instrument for the case this whole module was built for. A phone switched on after a
/// week offline decrypts thousands of messages, and the great majority are older than
/// `SYNC_WINDOW_MS` and dropped on the spot — correctly; that is the entire point of the
/// window. But a dropped message never reaches the queue. So the queue stays empty,
/// every poll comes back short, `CatchUpPacer` concludes there is no backlog, and the
/// "still syncing" spinner never appears.
///
/// The 2026-08-12 capture is exactly that: 3,367 messages decrypted, 754 admitted, 2,613
/// discarded — and for the first seven and a half minutes NOTHING crossed the FFI
/// boundary at all. The user watched a half-filled room list with no sign the app was
/// working, because by every signal the app had, it wasn't.
///
/// So the receive path reports itself here. [`Self::idle_ms`] is the signal that
/// matters: time since the last decrypted message, kept or thrown away. The counters are
/// the evidence a support bundle needs — until now both discard paths were a bare
/// `return` and a `log::debug!`, so a bundle could show that nothing old got THROUGH, but
/// never that the filter had fired at all.
///
/// The clock is passed in rather than read here, for the same reason as everything else
/// in this module: no dependencies, and the arithmetic (saturating on a backwards
/// wall-clock jump) is the part worth pinning by test.
#[derive(Default)]
pub struct IngestActivity {
    /// Wall-clock ms of the last decrypted message to reach the receive path; 0 = none
    /// yet.
    last_ms: u64,
    admitted: u64,
    outside_window: u64,
    already_seen: u64,
    /// Decrypted messages the three outcomes above never see — see [`Self::touch`].
    ancillary: u64,
}

impl IngestActivity {
    /// Record one decrypted message, whatever became of it.
    pub fn record(&mut self, what: Ingested, now_ms: u64) {
        self.advance_clock(now_ms);
        match what {
            Ingested::Admitted => self.admitted += 1,
            Ingested::OutsideWindow => self.outside_window += 1,
            Ingested::AlreadySeen => self.already_seen += 1,
        }
        if what == Ingested::Admitted {
            return;
        }
        let discarded = self.discarded();
        if discarded % DISCARD_LOG_EVERY == 0 {
            log::info!(
                "CATCHUP native: ingest discarded={discarded} (outsideWindow={} \
                 alreadySeen={}) admitted={} — these reach neither the queue nor Kotlin, \
                 so this line is the only trace they leave (ancillary={})",
                self.outside_window,
                self.already_seen,
                self.admitted,
                self.ancillary,
            );
        }
    }

    /// Never let the recorded time go backwards. A wall-clock correction (NTP, or the
    /// user changing the date) must not make a mid-drain receive path look idle for
    /// hours and switch the spinner off underneath a working sync.
    fn advance_clock(&mut self, now_ms: u64) {
        if now_ms > self.last_ms {
            self.last_ms = now_ms;
        }
    }

    /// A decrypted message that none of the three outcomes above will ever see.
    ///
    /// Receipts, typing notifications, profile updates and the ~18 other `Message`
    /// variants return from `push_relay_event` before the sync-window and replay gates,
    /// or fall off the end of it — so they never reach [`Self::record`]. They are still
    /// the receive path working, and on a replay they are the MAJORITY of it: the
    /// 2026-08-12 capture carried 958 read receipts against 754 actual messages.
    ///
    /// Leaving them out let [`Self::idle_ms`] climb through a receipt-heavy stretch
    /// until Kotlin's `endGraceMs` expired and ended the sync episode MID-SYNC — the
    /// spinner switching off, and `SaveCoalescer` flushing a whole-store encrypted write
    /// in the middle of the flood, which is the exact write it exists to withhold.
    ///
    /// So these advance the CLOCK but not the counters. `newWork` still excludes them
    /// deliberately: a burst of receipts is not work the user is waiting on and must not
    /// raise a spinner by itself — the same rule as [`Ingested::AlreadySeen`].
    pub fn touch(&mut self, now_ms: u64) {
        self.advance_clock(now_ms);
        self.ancillary += 1;
    }

    /// Messages decrypted and then thrown away, by either gate.
    pub fn discarded(&self) -> u64 {
        self.outside_window + self.already_seen
    }

    /// Every decrypted message seen, kept or not. Monotonic for the life of the process;
    /// Kotlin thresholds on the DELTA, so it never needs an absolute meaning.
    pub fn total(&self) -> u64 {
        self.admitted + self.discarded()
    }

    /// Ms since the last decrypted message. Saturating, so a backwards clock reports 0
    /// ("busy") rather than a huge number ("idle") — erring toward leaving the spinner ON
    /// is the safe direction.
    pub fn idle_ms(&self, now_ms: u64) -> u64 {
        if self.last_ms == 0 {
            return IDLE_NEVER_MS;
        }
        now_ms.saturating_sub(self.last_ms)
    }

    pub fn admitted(&self) -> u64 {
        self.admitted
    }
    pub fn outside_window(&self) -> u64 {
        self.outside_window
    }
    pub fn already_seen(&self) -> u64 {
        self.already_seen
    }
    pub fn ancillary(&self) -> u64 {
        self.ancillary
    }

    /// The payload `nativeIngestActivity` hands Kotlin. `depth` is passed in because this
    /// type deliberately knows nothing about the queue.
    pub fn snapshot_json(&self, now_ms: u64, depth: usize) -> Value {
        serde_json::json!({
            "idleMs": self.idle_ms(now_ms),
            "depth": depth,
            "total": self.total(),
            "admitted": self.admitted,
            "outsideWindow": self.outside_window,
            "alreadySeen": self.already_seen,
            // Diagnostic only. Deliberately outside `total`, so nothing thresholds on it.
            "ancillary": self.ancillary,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn msg(guid: &str) -> Value {
        json!({ "type": "message", "guid": guid, "text": "hi" })
    }

    /// A queue primed as the receive path primes it: every queued message's guid is
    /// also recorded in the replay guard.
    fn queue_n(n: usize) -> (InboundQueue, HashSet<String>) {
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        for i in 0..n {
            let guid = format!("G{i}");
            seen.insert(guid.clone());
            q.queue(&mut seen, msg(&guid));
        }
        (q, seen)
    }

    // ---- the cap -------------------------------------------------------------

    #[test]
    fn queue_never_exceeds_cap() {
        // The regression the freeze came from: this used to be a bare push_back, so a
        // backlog burst grew the queue without limit.
        let (q, _) = queue_n(INBOUND_CAP * 3);
        assert_eq!(q.len(), INBOUND_CAP);
    }

    #[test]
    fn overflow_drops_oldest_and_keeps_newest() {
        let (mut q, _) = queue_n(INBOUND_CAP + 5);
        let first = q.events.front().unwrap()["guid"].as_str().unwrap().to_string();
        let last = q.events.back().unwrap()["guid"].as_str().unwrap().to_string();
        assert_eq!(first, "G5", "oldest 5 should have been evicted");
        assert_eq!(last, format!("G{}", INBOUND_CAP + 4), "newest must survive");
        assert_eq!(q.dropped_total(), 5);
        let _ = q.drain_batch(POLL_BATCH_MAX);
    }

    #[test]
    fn dropped_events_are_unmarked_so_the_replay_redelivers_them() {
        // The safety property of the cap. If a guid stayed in `seen` after its event
        // was dropped, the replay guard would skip that message on every future connect
        // and the user would never see it.
        let (_, seen) = queue_n(INBOUND_CAP + 3);
        for i in 0..3 {
            assert!(!seen.contains(&format!("G{i}")), "dropped G{i} must be re-deliverable");
        }
        assert!(seen.contains(&format!("G{}", INBOUND_CAP + 2)), "retained events stay guarded");
    }

    #[test]
    fn events_without_a_guid_do_not_disturb_the_guard() {
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        seen.insert("KEEP".to_string());
        for _ in 0..(INBOUND_CAP + 10) {
            q.queue(&mut seen, json!({ "type": "sms_activation", "enabled": true }));
        }
        assert_eq!(q.len(), INBOUND_CAP);
        assert!(seen.contains("KEEP"));
    }

    // ---- the drain -----------------------------------------------------------

    #[test]
    fn drain_is_capped_and_leaves_the_remainder_queued() {
        // The core of the fix: one poll can never hand Kotlin the whole backlog.
        let (mut q, _) = queue_n(INBOUND_CAP);
        let batch = q.drain_batch(POLL_BATCH_MAX);
        assert_eq!(batch.len(), POLL_BATCH_MAX);
        assert_eq!(q.len(), INBOUND_CAP - POLL_BATCH_MAX);
    }

    #[test]
    fn drain_preserves_order_across_batches() {
        // Ordering matters downstream: a tapback or read receipt that arrived after its
        // target message must still be applied after it.
        let (mut q, _) = queue_n(POLL_BATCH_MAX * 3);
        let mut order = Vec::new();
        loop {
            let batch = q.drain_batch(POLL_BATCH_MAX);
            if batch.is_empty() {
                break;
            }
            for e in batch {
                order.push(e["guid"].as_str().unwrap().to_string());
            }
        }
        let expected: Vec<String> = (0..POLL_BATCH_MAX * 3).map(|i| format!("G{i}")).collect();
        assert_eq!(order, expected);
    }

    #[test]
    fn repeated_drains_empty_the_queue_and_then_return_nothing() {
        // What tells the transport catch-up is finished: a short batch, then an empty one.
        let (mut q, _) = queue_n(POLL_BATCH_MAX + 7);
        assert_eq!(q.drain_batch(POLL_BATCH_MAX).len(), POLL_BATCH_MAX);
        assert_eq!(q.drain_batch(POLL_BATCH_MAX).len(), 7);
        assert!(q.drain_batch(POLL_BATCH_MAX).is_empty());
    }

    #[test]
    fn a_full_backlog_is_delivered_in_bounded_chunks() {
        // End-to-end shape of catch-up after the fix: every event still gets through,
        // and no single hand-off is ever larger than POLL_BATCH_MAX.
        let (mut q, _) = queue_n(INBOUND_CAP);
        let mut total = 0usize;
        let mut largest = 0usize;
        loop {
            let batch = q.drain_batch(POLL_BATCH_MAX);
            if batch.is_empty() {
                break;
            }
            largest = largest.max(batch.len());
            total += batch.len();
        }
        assert_eq!(total, INBOUND_CAP, "nothing is lost, it is only paced");
        assert_eq!(largest, POLL_BATCH_MAX, "and no hand-off exceeds one batch");
        assert_eq!(q.delivered_total(), INBOUND_CAP as u64);
    }

    // ---- the counters that end up in an export-logs bundle -------------------

    #[test]
    fn peak_depth_records_how_close_the_burst_came_to_the_cap() {
        // This is the headroom number a support bundle is read for: a peak far below
        // the cap means the drain kept up, a peak pinned AT the cap means it did not.
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        for i in 0..600 {
            q.queue(&mut seen, msg(&format!("G{i}")));
        }
        assert_eq!(q.burst_peak_depth, 600);
        // Draining does not lower the recorded peak — it is the high-water mark for the
        // whole burst, not the current depth.
        q.drain_batch(POLL_BATCH_MAX);
        assert_eq!(q.burst_peak_depth, 600);
    }

    #[test]
    fn burst_counters_reset_once_the_queue_empties() {
        let (mut q, _) = queue_n(POLL_BATCH_MAX * 2);
        while !q.drain_batch(POLL_BATCH_MAX).is_empty() {}
        assert_eq!(q.burst_delivered, 0, "a finished burst must not bleed into the next");
        assert_eq!(q.burst_batches, 0);
        assert_eq!(q.burst_peak_depth, 0);
        assert!(!q.burst_saw_full_batch);
        // Lifetime totals persist — they are what the summary reports as context.
        assert_eq!(q.delivered_total(), (POLL_BATCH_MAX * 2) as u64);
    }

    #[test]
    fn a_trickle_of_live_messages_is_not_reported_as_a_burst() {
        // The summary line has to mean something. If every single arriving message
        // logged one, the line would be worthless in a bundle — and would itself become
        // the kind of log flood this work exists to remove.
        let mut q = InboundQueue::default();
        let mut seen = HashSet::new();
        for i in 0..30 {
            q.queue(&mut seen, msg(&format!("L{i}")));
            let batch = q.drain_batch(POLL_BATCH_MAX);
            assert_eq!(batch.len(), 1);
            assert!(!q.burst_saw_full_batch, "a single message is never a full batch");
        }
        assert_eq!(q.delivered_total(), 30);
    }

    #[test]
    fn drops_are_counted_per_burst_and_for_the_lifetime() {
        let (mut q, _) = queue_n(INBOUND_CAP + 120);
        assert_eq!(q.burst_dropped, 120);
        assert_eq!(q.dropped_total(), 120);
        while !q.drain_batch(POLL_BATCH_MAX).is_empty() {}
        assert_eq!(q.burst_dropped, 0, "burst counter resets");
        assert_eq!(q.dropped_total(), 120, "lifetime counter does not");
    }

    #[test]
    fn a_healthy_catch_up_reports_zero_drops() {
        // The success case the bundle should show: a few days of backlog fits under the
        // cap end to end, so nothing is dropped and nothing needs re-delivering.
        let (mut q, _) = queue_n(1_500);
        while !q.drain_batch(POLL_BATCH_MAX).is_empty() {}
        assert_eq!(q.dropped_total(), 0);
        assert_eq!(q.delivered_total(), 1_500);
    }

    // ---- ingest activity -----------------------------------------------------

    #[test]
    fn a_discard_only_burst_still_reads_as_busy() {
        // THE regression this type exists for. Every message is older than the sync
        // window, so the queue never sees one and stays empty — but the receive path is
        // working flat out, and Kotlin has to be able to tell.
        let q = InboundQueue::default();
        let mut a = IngestActivity::default();
        let mut t = 1_000_000u64;
        for _ in 0..2_490 {
            a.record(Ingested::OutsideWindow, t);
            t += 120; // ~8/s, the rate the 08-12 capture actually ran at
        }
        assert!(q.is_empty(), "nothing was ever queued");
        assert_eq!(a.idle_ms(t), 120, "yet the receive path was busy 120ms ago");
        assert_eq!(a.total(), 2_490);
        assert_eq!(a.admitted(), 0);
        assert_eq!(a.discarded(), 2_490);
    }

    #[test]
    fn receipt_only_traffic_keeps_the_receive_path_looking_busy() {
        // THE F1 regression. A replay is mostly receipts, and receipts never reach
        // record() — they return from push_relay_event before either gate. Before
        // touch() existed, a stretch like this let idle_ms climb past Kotlin's
        // endGraceMs and end the sync episode while the sync was still running.
        let mut a = IngestActivity::default();
        a.record(Ingested::Admitted, 1_000);
        let mut t = 1_000u64;
        for _ in 0..200 {
            t += 120; // ~8/s, the rate the 08-12 capture ran at
            a.touch(t);
        }
        assert_eq!(a.idle_ms(t), 0, "receipts ARE the receive path working");
        assert_eq!(a.total(), 1, "but they are not work the user is waiting on");
        assert_eq!(a.ancillary(), 200);
    }

    #[test]
    fn receipt_only_traffic_cannot_announce_an_episode() {
        // The other half of the rule: keeping an episode alive is not the same as
        // starting one. Kotlin thresholds on admitted + outsideWindow, so a pure
        // receipt burst must leave every one of those counters at zero.
        let mut a = IngestActivity::default();
        for i in 0..500 {
            a.touch(i);
        }
        assert_eq!(a.admitted(), 0);
        assert_eq!(a.discarded(), 0);
        assert_eq!(a.total(), 0, "nothing here can cross minEvents");
    }

    #[test]
    fn idle_ms_reports_never_before_the_first_message() {
        let a = IngestActivity::default();
        assert_eq!(a.idle_ms(5_000), IDLE_NEVER_MS);
        // And it has to survive JSON → Kotlin Long. u64::MAX would not.
        assert!(IDLE_NEVER_MS < i64::MAX as u64);
    }

    #[test]
    fn a_backwards_clock_reports_busy_not_idle() {
        // An NTP correction or a user changing the date mid-drain must not switch the
        // spinner off. Erring toward "busy" is the safe direction.
        let mut a = IngestActivity::default();
        a.record(Ingested::Admitted, 10_000);
        assert_eq!(a.idle_ms(5_000), 0, "a now BEFORE the last record is not 'idle for ages'");
        a.record(Ingested::Admitted, 5_000);
        assert_eq!(a.idle_ms(10_000), 0, "and the recorded time never regresses");
    }

    #[test]
    fn the_three_outcomes_are_counted_separately() {
        let mut a = IngestActivity::default();
        a.record(Ingested::Admitted, 1);
        a.record(Ingested::Admitted, 2);
        a.record(Ingested::OutsideWindow, 3);
        a.record(Ingested::AlreadySeen, 4);
        a.record(Ingested::AlreadySeen, 5);
        assert_eq!(a.admitted(), 2);
        assert_eq!(a.outside_window(), 1);
        assert_eq!(a.already_seen(), 2);
        assert_eq!(a.discarded(), 3);
        assert_eq!(a.total(), 5);
    }

    #[test]
    fn the_snapshot_carries_queue_depth_and_the_counters() {
        let mut a = IngestActivity::default();
        a.record(Ingested::OutsideWindow, 1_000);
        let snap = a.snapshot_json(1_250, 7);
        assert_eq!(snap["idleMs"], 250);
        assert_eq!(snap["depth"], 7);
        assert_eq!(snap["total"], 1);
        assert_eq!(snap["admitted"], 0);
        assert_eq!(snap["outsideWindow"], 1);
        assert_eq!(snap["alreadySeen"], 0);
    }

    #[test]
    fn the_total_is_monotonic_so_kotlin_can_threshold_on_a_delta() {
        // Kotlin decides "this is an episode, not one busy moment" by differencing this
        // counter, so it must only ever climb.
        let mut a = IngestActivity::default();
        let mut last = 0u64;
        for i in 0..500u64 {
            a.record(
                match i % 3 {
                    0 => Ingested::Admitted,
                    1 => Ingested::OutsideWindow,
                    _ => Ingested::AlreadySeen,
                },
                i,
            );
            assert!(a.total() > last);
            last = a.total();
        }
        assert_eq!(a.total(), 500);
    }
}
