//! The bounded inbound event queue: everything the receive path produces waits here
//! until Kotlin's `nativePollEvents` picks it up.
//!
//! This lives in its own module — rather than inline in `lib.rs` — because it is the
//! part of the catch-up path with real failure modes (unbounded growth, oversized
//! drains) and it is the part worth unit-testing. Nothing here touches JNI, rustpush
//! or any Android API, so the tests below are plain `cargo test`.
//!
//! ## Why this exists
//!
//! Apple re-sends its entire stored backlog on every APS connect (rustpush's
//! `IMClient::setup_conn` asks for it explicitly — madrid command 160, "flush cache").
//! That IS the catch-up mechanism: it's how messages received while the app was closed
//! arrive. The cost is that a phone switched on after a day or two offline decrypts
//! thousands of messages in a burst, far faster than the Kotlin side consumes them.
//!
//! Before this module, two things were unbounded:
//!
//! 1. the queue itself, which grew until the burst was consumed; and
//! 2. the drain, which handed the WHOLE queue to Kotlin in one `serde_json::to_string`
//!    → one Java `String` (UTF-16, 2x the bytes) → one `parseToJsonElement` tree
//!    (~10x again in short-lived objects) → one enormous repository batch.
//!
//! On a 938 MB phone with a ~15 MB app heap that spike is fatal: the low-memory killer
//! takes the foreground process, and the user experiences it as the phone freezing on
//! first launch. Bounding both turns one unsurvivable spike into many small ones.

use serde_json::Value;
use std::collections::{HashSet, VecDeque};

/// Hard ceiling on the queue length. Sized so an ordinary few-days backlog still fits
/// end to end without dropping anything, while a pathological burst stays bounded.
pub const INBOUND_CAP: usize = 2_000;

/// Max events a single `nativePollEvents` call may return.
///
/// This is the number that actually fixes the freeze. Throughput is unaffected: the
/// transport polls back-to-back while batches come back full (see
/// `NativeRustPushTransport.startPolling`), so catch-up takes the same wall-clock time
/// — it just never allocates more than one batch at a time.
pub const POLL_BATCH_MAX: usize = 50;

/// Queue one relay-wire event, enforcing [`INBOUND_CAP`].
///
/// On overflow the OLDEST event is dropped, not the newest: a live message the user is
/// waiting on matters more than one more item of week-old backlog.
///
/// Dropping is *recoverable*, which is what makes the cap safe. Every dropped event's
/// guid is also removed from `seen` (the replay guard), so Apple's next backlog replay
/// re-delivers it instead of the guard silently swallowing it forever. Without that
/// removal, a capacity drop would be permanent data loss — the guard would see the guid
/// and skip the message on every subsequent connect.
///
/// Events with no `guid` field (control events like `sms_activation`, or `chat_read`,
/// which carries `messageGuid`) simply have nothing to un-mark; they are regenerated by
/// the next connect's state sync rather than by the replay guard.
pub fn queue_event(inbound: &mut VecDeque<Value>, seen: &mut HashSet<String>, event: Value) {
    while inbound.len() >= INBOUND_CAP {
        let Some(dropped) = inbound.pop_front() else { break };
        if let Some(guid) = dropped.get("guid").and_then(|g| g.as_str()) {
            seen.remove(guid);
        }
    }
    inbound.push_back(event);
}

/// Take at most `max` events off the front of the queue, leaving the rest for the next
/// poll. Order is preserved: the repository folds messages in arrival order, and a
/// tapback or status update that arrived after its target message must stay after it.
pub fn drain_batch(inbound: &mut VecDeque<Value>, max: usize) -> Vec<Value> {
    let n = inbound.len().min(max);
    inbound.drain(..n).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn msg(guid: &str) -> Value {
        json!({ "type": "message", "guid": guid, "text": "hi" })
    }

    /// A queue/seen pair primed as the receive path primes it: every queued message's
    /// guid is also recorded in the replay guard.
    fn queue_n(n: usize) -> (VecDeque<Value>, HashSet<String>) {
        let mut inbound = VecDeque::new();
        let mut seen = HashSet::new();
        for i in 0..n {
            let guid = format!("G{i}");
            seen.insert(guid.clone());
            queue_event(&mut inbound, &mut seen, msg(&guid));
        }
        (inbound, seen)
    }

    #[test]
    fn queue_never_exceeds_cap() {
        // The regression the freeze came from: this used to be a bare push_back, so a
        // backlog burst grew the queue without limit.
        let (inbound, _) = queue_n(INBOUND_CAP * 3);
        assert_eq!(inbound.len(), INBOUND_CAP);
    }

    #[test]
    fn overflow_drops_oldest_and_keeps_newest() {
        let (inbound, _) = queue_n(INBOUND_CAP + 5);
        let first = inbound.front().unwrap()["guid"].as_str().unwrap().to_string();
        let last = inbound.back().unwrap()["guid"].as_str().unwrap().to_string();
        assert_eq!(first, format!("G{}", 5), "oldest 5 should have been evicted");
        assert_eq!(last, format!("G{}", INBOUND_CAP + 4), "newest must survive");
    }

    #[test]
    fn dropped_events_are_unmarked_so_the_replay_redelivers_them() {
        // The safety property of the cap. If a guid stayed in `seen` after its event was
        // dropped, the replay guard would skip that message on every future connect and
        // the user would never see it.
        let (_, seen) = queue_n(INBOUND_CAP + 3);
        for i in 0..3 {
            assert!(!seen.contains(&format!("G{i}")), "dropped G{i} must be re-deliverable");
        }
        assert!(seen.contains(&format!("G{}", INBOUND_CAP + 2)), "retained events stay guarded");
    }

    #[test]
    fn events_without_a_guid_do_not_disturb_the_guard() {
        let mut inbound = VecDeque::new();
        let mut seen = HashSet::new();
        seen.insert("KEEP".to_string());
        for _ in 0..(INBOUND_CAP + 10) {
            queue_event(&mut inbound, &mut seen, json!({ "type": "sms_activation", "enabled": true }));
        }
        assert_eq!(inbound.len(), INBOUND_CAP);
        assert!(seen.contains("KEEP"));
    }

    #[test]
    fn drain_is_capped_and_leaves_the_remainder_queued() {
        // The core of the fix: one poll can never hand Kotlin the whole backlog.
        let (mut inbound, _) = queue_n(INBOUND_CAP);
        let batch = drain_batch(&mut inbound, POLL_BATCH_MAX);
        assert_eq!(batch.len(), POLL_BATCH_MAX);
        assert_eq!(inbound.len(), INBOUND_CAP - POLL_BATCH_MAX);
    }

    #[test]
    fn drain_preserves_order_across_batches() {
        // Ordering matters downstream: a tapback or read receipt that arrived after its
        // target message must still be applied after it.
        let (mut inbound, _) = queue_n(POLL_BATCH_MAX * 3);
        let mut seen_order = Vec::new();
        loop {
            let batch = drain_batch(&mut inbound, POLL_BATCH_MAX);
            if batch.is_empty() {
                break;
            }
            for e in batch {
                seen_order.push(e["guid"].as_str().unwrap().to_string());
            }
        }
        let expected: Vec<String> = (0..POLL_BATCH_MAX * 3).map(|i| format!("G{i}")).collect();
        assert_eq!(seen_order, expected);
    }

    #[test]
    fn repeated_drains_empty_the_queue_and_then_return_nothing() {
        // What tells the transport catch-up is finished: a short batch, then an empty one.
        let (mut inbound, _) = queue_n(POLL_BATCH_MAX + 7);
        assert_eq!(drain_batch(&mut inbound, POLL_BATCH_MAX).len(), POLL_BATCH_MAX);
        assert_eq!(drain_batch(&mut inbound, POLL_BATCH_MAX).len(), 7);
        assert!(drain_batch(&mut inbound, POLL_BATCH_MAX).is_empty());
    }

    #[test]
    fn a_full_backlog_is_delivered_in_bounded_chunks() {
        // End-to-end shape of catch-up after the fix: every event still gets through,
        // and no single hand-off is ever larger than POLL_BATCH_MAX.
        let (mut inbound, _) = queue_n(INBOUND_CAP);
        let mut total = 0usize;
        let mut largest = 0usize;
        loop {
            let batch = drain_batch(&mut inbound, POLL_BATCH_MAX);
            if batch.is_empty() {
                break;
            }
            largest = largest.max(batch.len());
            total += batch.len();
        }
        assert_eq!(total, INBOUND_CAP, "nothing is lost, it is only paced");
        assert_eq!(largest, POLL_BATCH_MAX, "and no hand-off exceeds one batch");
    }
}
